### ISSUE TITLE
[SOLVED] adding support for Legion 5i Pro 2022

### ISSUE THREAD

**Issue by BehradJi** [imShara/l5p-kbl#10]
is there anything I can provide for adding support for L5P 2022?
right now I am getting this error:
```
Traceback (most recent call last):
  File "/usr/bin/l5p-kbl", line 240, in <module>
    controller = LedController()
  File "/usr/bin/l5p-kbl", line 63, in __init__
    raise ValueError("Light device not found")
ValueError: Light device not found
```
my lsusb output:
```
Bus 004 Device 002: ID 05e3:0620 Genesys Logic, Inc. GL3523 Hub
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 005: ID 048d:c975 Integrated Technology Express, Inc. ITE Device(8295)
Bus 003 Device 003: ID 048d:c102 Integrated Technology Express, Inc. ITE Device(8910)
Bus 003 Device 010: ID 093a:2510 Pixart Imaging, Inc. Optical Mouse
Bus 003 Device 002: ID 05e3:0610 Genesys Logic, Inc. Hub
Bus 003 Device 006: ID 8087:0033 Intel Corp. 
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

```

**Comment by BehradJi** [comment]
So interestingly, after a little bit of searching I found this [repo](https://github.com/dpfistner/l5p-kbl) which is a fork of [imShara](https://github.com/imShara/l5p-kbl/) and added support for Legion 5i Pro 2022, I hope this repo merge that.
